arch:configs: set config_debug_fs
All HALs in device manifest are declared in FCM <= level 5
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 5, Kernel config errors:
    For config CONFIG_DEBUG_FS, value = y but required n
: Success
INCOMPATIBLE